### ISSUE TITLE
[major bug] `is_link` used as intended but assigned as `is_pe`

### ISSUE THREAD

**Issue by XakerTwo** [LINBIT/generate-cat-file#1]
[generate-cat-file.c @ 526](https://github.com/LINBIT/generate-cat-file/blob/main/generate-cat-file.c#L526)
if (not is_link) - `encode_spc_image_data`    // encode spc for PE file
else - `encode_spc_link`     // encode spc for non PE file

but on parsing files there inversed assigning
[generate-cat-file.c @ 736](https://github.com/LINBIT/generate-cat-file/blob/main/generate-cat-file.c#L736)
if (is_pe) - is_link = true & guid = "{DE35...}"    // but should be for "not is_pe"
else - is_link = false & guid = "{C689...}"    // but should be for "is_pe"

**Comment by johannesthoma** [comment]
Oops you're right. I will do some more checks but I think I take this commit.

**Comment by johannesthoma** [comment]
Hi thanks for your patch, I merged it to main. Closing this issue.
