### ISSUE TITLE
[potential bug] during utf16 encoding there possibility to get "IndexOutOfRange" error

### ISSUE THREAD

**Issue by XakerTwo** [LINBIT/generate-cat-file#2]
while in C there no such exception, think you understand idea. it can cause access violation or in worst case silent memory corruption

[encode_string_as_utf16() - generate-cat-file.c @ 277](https://github.com/LINBIT/generate-cat-file/blob/main/generate-cat-file.c#L277)
buffer declared as `unsigned short utf16[1000];`
loop defined as `for (i = 0; s[i] != '\0' && i < sizeof(utf16)/sizeof(utf16[0]); i++)`
and then, after the loop, buffer accessed as `if (s[i] == '\0') utf16[i] = 0;` // inverted for clarity
besides the fact that it can be explicitly optimized as
```c
int l = sizeof(utf16)/sizeof(utf16[0]);
for (i = 0; i < l && s[i] != '\0'; ++i)
```
input string can be exactly 1000 chars of length and the 1001 element at index 1000 will be accessed, that is out of buffer range

it can be easily fixed by changing condition to
`if (i >= l) fatal("string too long\n");`

loop will be exited any way, but only in too long string case it will be leaved with `i` equals to buffer length

**Comment by johannesthoma** [comment]
Hi thanks for your patch, I merged it to main. Closing this issue.
