### ISSUE TITLE
[bug] incorrect default OS values for Win 10

### ISSUE THREAD

**Issue by XakerTwo** [LINBIT/generate-cat-file#4]
[default values - generate-cat-file.c @ 758](https://github.com/LINBIT/generate-cat-file/blob/main/generate-cat-file.c#L758)
based on other cat files Win10(and Win11) should has the following values
`OS` = [`Server`] + `_v100` + [`_X64`] + [`_Vb`] (`_X86` ommits since Win 8.1; `_Vb` is short codename of Win10 or version of Win11 )
`OSAttr` = `2:10.0`

**Comment by johannesthoma** [comment]
Hi @XakerTwo thank you for you contributions. Sorry for the late
answer I was on vacation last week.

Do you have the possibility to send pull requests? If not, no problem,
just let me know. May I ask (because I am curious) if you intend to
use the tool for writing drivers?

**Comment by XakerTwo** [comment]
well, my use case atleast unordinary, but mostly for "academic purpose" - i was just looking for a light-weight tool to generate cat file due to modification of .inf file. WDK was the last tool for such a simple action. So i found your tool and, during adapting it to my goals, found few issues, reported here.

And about PR - should i include other issues? (except for the 3rd one, cuz not fully implemented it yet myself)

**Comment by johannesthoma** [comment]
Hi, thanks for letting me know about your use case.

If you can please open pull requests for each issue separately (this is the first time
I get more than trivial pull requests, so I have not that much experience as a maintainer ...)
I think separate pull requests would make most sense in that case. You can also
make one pull request if that is less work for you, but please use separate commits for
each issue.

Thanks a lot again for your contribution :)

**Comment by johannesthoma** [comment]
And thanks for digging into my minimallistic C-source code :)

**Comment by johannesthoma** [comment]
Hi thanks for your patch, I merged it to main. Closing this issue.
